apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: buom01
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 10.10.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: buom01/nginx
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: buom01
spec:
  ports:
  - name: http
    protocol: TCP
    port: 5050
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 10.10.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: buom01/wordpress
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: buom01
spec:
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 10.10.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: buom01/phpmyadmin
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: buom01
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 10.10.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: buom01/grafana
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: ftps 
  annotations:
    metallb.universe.tf/allow-shared-ip: buom01
spec:
  ports:
  - name: ftp
    protocol: TCP
    port: 21
    targetPort: 21
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 10.10.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: buom01/ftps
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: buom01
spec:
  ports:
  - name: sql 
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
  loadBalancerIP: 10.10.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: buom01/mysql
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: buom01
spec:
  ports:
  - name: influx
    protocol: TCP
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP
  loadBalancerIP: 10.10.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: buom01/influxdb
        imagePullPolicy: Never
