{
 "title": "FTPS",
 "description": "Monitor FTPS",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory usage",
   "type": "graph",
   "description": "Show RSS (in RAM) memory and total memory usage",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mo" } },
   "yaxes": [
    { "format": "Mo" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (memory_rss_bytes / 1024 / 1024 ), (memory_usage_bytes / 1024 / 1024 ) FROM \"kubernetes_pod_container\" WHERE container_name = 'ftps'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "description": "Disk usage over time",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mo" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (rootfs_used_bytes / 1024 / 1024) FROM \"kubernetes_pod_container\" WHERE container_name = 'ftps'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Core usage",
   "type": "graph",
   "description": "Representing CPU usage in cores",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (cpu_usage_nanocores / 1000000000) FROM \"kubernetes_pod_container\" WHERE container_name = 'ftps'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (rootfs_used_bytes / rootfs_available_bytes) FROM \"kubernetes_pod_container\" WHERE container_name = 'ftps'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}